package com.example.feature.auth

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.util.Log
import com.example.R
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

data class AuthUser(
    val uid: String,
    val displayName: String?,
    val email: String?,
    val photoUrl: String?
)

fun FirebaseUser.toAuthUser(): AuthUser {
    return AuthUser(
        uid = uid,
        displayName = displayName ?: email?.substringBefore('@') ?: "Shinobi Ninja",
        email = email,
        photoUrl = photoUrl?.toString()
    )
}

class AuthRepository(private val context: Context) {

    private val isFirebaseInitialized: Boolean by lazy {
        try {
            if (FirebaseApp.getApps(context).isEmpty()) {
                FirebaseApp.initializeApp(context)
            }
            true
        } catch (e: Exception) {
            Log.w("AuthRepository", "Firebase initialization deferred: ${e.message}")
            false
        }
    }

    private val firebaseAuth: FirebaseAuth?
        get() {
            return try {
                if (isFirebaseInitialized) FirebaseAuth.getInstance() else null
            } catch (e: Exception) {
                Log.w("AuthRepository", "FirebaseAuth not available: ${e.message}")
                null
            }
        }

    val currentUser: AuthUser?
        get() = firebaseAuth?.currentUser?.toAuthUser()

    val authStateFlow: Flow<AuthUser?> = callbackFlow {
        val auth = firebaseAuth
        if (auth == null) {
            trySend(null)
            awaitClose { }
        } else {
            val listener = FirebaseAuth.AuthStateListener { fa ->
                trySend(fa.currentUser?.toAuthUser())
            }
            auth.addAuthStateListener(listener)
            awaitClose {
                auth.removeAuthStateListener(listener)
            }
        }
    }

    fun getGoogleSignInClient(activity: Activity): GoogleSignInClient {
        // Try reading default_web_client_id from string resources (auto-generated by google-services plugin if google-services.json is present)
        val defaultClientIdRes = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName
        )

        val gsoBuilder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()

        if (defaultClientIdRes != 0) {
            try {
                val serverClientId = context.getString(defaultClientIdRes)
                if (serverClientId.isNotBlank()) {
                    gsoBuilder.requestIdToken(serverClientId)
                }
            } catch (e: Exception) {
                Log.w("AuthRepository", "Could not load default_web_client_id: ${e.message}")
            }
        }

        return GoogleSignIn.getClient(activity, gsoBuilder.build())
    }

    suspend fun signInWithGoogleIntent(data: Intent?): Result<AuthUser> {
        return try {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            val account = task.getResult(ApiException::class.java)
            val idToken = account.idToken

            val auth = firebaseAuth
            if (auth != null && idToken != null) {
                val credential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = auth.signInWithCredential(credential).await()
                val user = authResult.user?.toAuthUser()
                    ?: throw IllegalStateException("Firebase user was null after sign-in")
                Result.success(user)
            } else {
                // Fallback to Google Account profile directly if Firebase Auth is not yet configured with google-services.json
                val fallbackUser = AuthUser(
                    uid = account.id ?: "google_user",
                    displayName = account.displayName ?: account.givenName ?: "Shinobi Ninja",
                    email = account.email,
                    photoUrl = account.photoUrl?.toString()
                )
                Result.success(fallbackUser)
            }
        } catch (e: Exception) {
            Log.e("AuthRepository", "Google sign-in error", e)
            Result.failure(e)
        }
    }

    fun signOut(activity: Activity, onComplete: () -> Unit = {}) {
        try {
            firebaseAuth?.signOut()
            val client = getGoogleSignInClient(activity)
            client.signOut().addOnCompleteListener {
                onComplete()
            }
        } catch (e: Exception) {
            Log.e("AuthRepository", "Error during sign out", e)
            onComplete()
        }
    }
}
